---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
     upgrade: dist
     update_cache: yes


- hosts: web_servers
  become: true
  tasks:



  - name: install apache and apache2 for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt:
      name:
        - apache2
        - php
      state: latest

  - name: copy default html file for site
    tags: apaache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644


